dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm-3.24
  - nightly
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm-3.24
    - php: nightly
    - php: 7.4
  fast_finish: true

sudo: false

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  # Build job specific tweaks
  - >
    if [ $(phpenv version-name) == "5.5" ]; then
      rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    fi
  - >
    if [ $(phpenv version-name) != "hhvm-3.24" ] && [ $(phpenv version-name) != "nightly" ]; then
      echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  - >
    if { [ $(phpenv version-name) == "7.2" ] || [ $(phpenv version-name) == "7.3" ] || [ $(phpenv version-name) == "7.4" ] ; } && [ -v COMPOSER_OPTS ]; then
      composer require --dev phpunit/phpunit "～5.7.27"
    fi
  # Resolve dependencies
  - composer --version
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source --profile
  # Install Proxy
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_11.x" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo apt-get install -y npm
  - sudo npm i -g n --force -g --registry=https://registry.npm.taobao.org
  - sudo n latest
  - sudo npm install o_o -g --registry=https://registry.npm.taobao.org

script:
  # Start Proxy
  - sudo o_o &
  # Unit Test
  - test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
